# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b5335b8394797c0ffa1f2ebf2e30703268c3d1a52629aa18320174bfd86990601dc9f35582f5d1b63f46611fc8d4e40de7944b33d331406041bc678e02fae87

test:
  secret_key_base: ae363c231a47c86e4590ce5809262d0018d0f9a48eeb82a87b917b150fea4b8a38c5518385e14dfe92f3feb8bed608d2f79e0be601371571da63e4ceb1564bfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
